#include "plugin.h"
#include "CLEO.h"
using namespace plugin;
class FileSystemOperations{
public:
 FileSystemOperations(){if(CLEO_GetVersion()>=CLEO_VERSION){CLEO_RegisterOpcode(0x0B00,Script_FS_DeleteFile);CLEO_RegisterOpcode(0x0B01,Script_FS_DeleteDirectory);CLEO_RegisterOpcode(0x0B02,Script_FS_MoveFile);CLEO_RegisterOpcode(0x0B03,Script_FS_MoveDir);CLEO_RegisterOpcode(0x0B04,Script_FS_CopyFile);CLEO_RegisterOpcode(0x0B05,Script_FS_CopyDir);}else MessageBox(HWND_DESKTOP,"An incorrect version of CLEO was loaded.","FileSystemOperations.cleo",MB_ICONERROR);}
 static OpcodeResult WINAPI Script_FS_DeleteFile(CScriptThread*t){char p[MAX_PATH];CLEO_ReadStringOpcodeParam(t,p,sizeof(p));CLEO_SetThreadCondResult(t,DeleteFile(p));return OR_CONTINUE;}
 static BOOL DeleteDir(const char*p){char m[MAX_PATH],s[MAX_PATH];HANDLE h;WIN32_FIND_DATA w={};sprintf(m,"%s\\*",p);if((h=FindFirstFile(m,&w))!=INVALID_HANDLE_VALUE){do{sprintf(s,"%s\\%s",p,w.cFileName);if(w.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY){if(strcmp(w.cFileName,".")&&strcmp(w.cFileName,"..")&&!DeleteDir(s)){FindClose(h);return FALSE;}}else{SetFileAttributes(s,FILE_ATTRIBUTE_NORMAL);if(!DeleteFile(s)){FindClose(h);return FALSE;}}}while(FindNextFile(h,&w));FindClose(h);}return RemoveDirectory(p);}
 static OpcodeResult WINAPI Script_FS_DeleteDirectory(CScriptThread*t){char p[MAX_PATH];int all;CLEO_ReadStringOpcodeParam(t,p,sizeof(p));all=static_cast<int>(CLEO_GetIntOpcodeParam(t));CLEO_SetThreadCondResult(t,all?DeleteDir(p):RemoveDirectory(p));return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_FS_MoveFile(CScriptThread*t){char p[MAX_PATH],n[MAX_PATH];CLEO_ReadStringOpcodeParam(t,p,sizeof(p));CLEO_ReadStringOpcodeParam(t,n,sizeof(n));BOOL r=(GetFileAttributes(p)&FILE_ATTRIBUTE_DIRECTORY);if(!r)r=MoveFile(p,n);CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_FS_MoveDir(CScriptThread*t){char p[MAX_PATH],n[MAX_PATH];CLEO_ReadStringOpcodeParam(t,p,sizeof(p));CLEO_ReadStringOpcodeParam(t,n,sizeof(n));BOOL r=(GetFileAttributes(p)&FILE_ATTRIBUTE_DIRECTORY);if(r)r=MoveFile(p,n);CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_FS_CopyFile(CScriptThread*t){char p[MAX_PATH],n[MAX_PATH];DWORD a;BOOL r;CLEO_ReadStringOpcodeParam(t,p,sizeof(p));CLEO_ReadStringOpcodeParam(t,n,sizeof(n));if(r=CopyFile(p,n,FALSE)){a=GetFileAttributes(p);SetFileAttributes(n,a);}CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
 static BOOL CopyDir(const char*p,const char*n){char m[MAX_PATH],s[MAX_PATH],d[MAX_PATH];DWORD a;HANDLE h;WIN32_FIND_DATA w={};if(!CreateDirectory(n,NULL))return FALSE;sprintf(m,"%s\\*",p);if((h=FindFirstFile(m,&w))!=INVALID_HANDLE_VALUE){do{sprintf(s,"%s\\%s",p,w.cFileName);sprintf(d,"%s\\%s",n,w.cFileName);if(w.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY){if(strcmp(w.cFileName,".")&&strcmp(w.cFileName,"..")&&!CopyDir(s,d)){FindClose(h);return FALSE;}}else if(CopyFile(s,d,FALSE)){a=GetFileAttributes(s);SetFileAttributes(d,a);}else{FindClose(h);return FALSE;}}while(FindNextFile(h,&w));FindClose(h);}return TRUE;}
 static OpcodeResult WINAPI Script_FS_CopyDir(CScriptThread*t){char p[MAX_PATH],n[MAX_PATH];CLEO_ReadStringOpcodeParam(t,p,sizeof(p));CLEO_ReadStringOpcodeParam(t,n,sizeof(n));CLEO_SetThreadCondResult(t,CopyDir(p,n));return OR_CONTINUE;}
} fileSystemOperations;