#include <cstdio>
#include "CLEO.h"
class IniFiles{
public:
 IniFiles(){if(CLEO_GetVersion()>=CLEO_VERSION){CLEO_RegisterOpcode(0x0AF0,Script_InifileGetInt);CLEO_RegisterOpcode(0x0AF1,Script_InifileWriteInt);CLEO_RegisterOpcode(0x0AF2,Script_InifileGetFloat);CLEO_RegisterOpcode(0x0AF3,Script_InifileWriteFloat);CLEO_RegisterOpcode(0x0AF4,Script_InifileReadString);CLEO_RegisterOpcode(0x0AF5,Script_InifileWriteString);}else MessageBox(HWND_DESKTOP,"An incorrect version of CLEO was loaded.","IniFiles.cleo",MB_ICONERROR);}
 static char* MakeFullPath(char*p,char*d){if(p[1]!=':'){GetCurrentDirectory(MAX_PATH,d);strcat(d,"\\");strcat(d,p);}else strcpy(d,p);return d;}
 static OpcodeResult WINAPI Script_InifileGetInt(CScriptThread*t){char i[MAX_PATH],p[100],s[100],k[100];int r;CLEO_ReadStringPointerOpcodeParam(t,p,sizeof(p));CLEO_ReadStringPointerOpcodeParam(t,s,sizeof(s));CLEO_ReadStringPointerOpcodeParam(t,k,sizeof(k));MakeFullPath(p,i);r=GetPrivateProfileInt(s,k,0x80000000,i);CLEO_SetIntOpcodeParam(t,r);CLEO_SetThreadCondResult(t,r!=0x80000000);return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_InifileWriteInt(CScriptThread*t){char i[MAX_PATH],p[100],s[100],k[100],v[100];DWORD val=CLEO_GetIntOpcodeParam(t);CLEO_ReadStringPointerOpcodeParam(t,p,sizeof(p));CLEO_ReadStringPointerOpcodeParam(t,s,sizeof(s));CLEO_ReadStringPointerOpcodeParam(t,k,sizeof(k));MakeFullPath(p,i);BOOL r=WritePrivateProfileString(s,k,_itoa(val,v,10),i);CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_InifileGetFloat(CScriptThread*t){char i[MAX_PATH],p[100],s[100],k[100],v[100];float val=0.0f;CLEO_ReadStringPointerOpcodeParam(t,p,sizeof(p));CLEO_ReadStringPointerOpcodeParam(t,s,sizeof(s));CLEO_ReadStringPointerOpcodeParam(t,k,sizeof(k));MakeFullPath(p,i);BOOL r=GetPrivateProfileString(s,k,NULL,v,sizeof(v),i);if(r){val=static_cast<float>(atof(v));CLEO_SetFloatOpcodeParam(t,val);}else CLEO_SkipOpcodeParams(t,1);CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_InifileWriteFloat(CScriptThread*t){char i[MAX_PATH],p[100],s[100],k[100],v[100];float val=CLEO_GetFloatOpcodeParam(t);CLEO_ReadStringPointerOpcodeParam(t,p,sizeof(p));CLEO_ReadStringPointerOpcodeParam(t,s,sizeof(s));CLEO_ReadStringPointerOpcodeParam(t,k,sizeof(k));MakeFullPath(p,i);sprintf(v,"%g",val);BOOL r=WritePrivateProfileString(s,k,v,i);CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_InifileReadString(CScriptThread*t){char i[MAX_PATH],p[100],s[100],k[100],v[100],*q;CLEO_ReadStringPointerOpcodeParam(t,p,sizeof(p));CLEO_ReadStringPointerOpcodeParam(t,s,sizeof(s));CLEO_ReadStringPointerOpcodeParam(t,k,sizeof(k));MakeFullPath(p,i);BOOL r=GetPrivateProfileString(s,k,NULL,v,sizeof(v),i);if(r){switch(CLEO_GetOperandType(t)){case globalVarVString:case localVarVString:case globalVarSString:case localVarSString:CLEO_WriteStringOpcodeParam(t,v);break;default:q=reinterpret_cast<char*>(CLEO_GetIntOpcodeParam(t));strcpy(q,v);}}else CLEO_SkipOpcodeParams(t,1);CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
 static OpcodeResult WINAPI Script_InifileWriteString(CScriptThread*t){char i[MAX_PATH],p[100],s[100],k[100],v[100],*q;switch(CLEO_GetOperandType(t)){case globalVarVString:case localVarVString:case globalVarSString:case localVarSString:CLEO_ReadStringPointerOpcodeParam(t,v,sizeof(v));break;default:q=reinterpret_cast<char*>(CLEO_GetIntOpcodeParam(t));strcpy(v,q);}CLEO_ReadStringPointerOpcodeParam(t,p,sizeof(p));CLEO_ReadStringPointerOpcodeParam(t,s,sizeof(s));CLEO_ReadStringPointerOpcodeParam(t,k,sizeof(k));MakeFullPath(p,i);BOOL r=WritePrivateProfileString(s,k,v,i);CLEO_SetThreadCondResult(t,r);return OR_CONTINUE;}
} iniFiles;